project/ImageHub/config/routes.rb
Rails.application.routes.draw do

  get 'public/about'

  get 'public/game'

  root to: 'albums#index'

  devise_for :users
  resources :images
  resources :albums
  resources :users

end

project/ImageHub/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  belongs_to :user
  has_many :images

  validates :user, presence: true
end

project/ImageHub/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name)
    end
end

project/ImageHub/app/helpers/albums_helper.rb
module AlbumsHelper
end

project/ImageHub/app/views/albums/_albums.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th id="asdf">Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% albums.each do |album| %>
      <tr>
        <td id="yyy" class='xxx'><%= album.name %></td>
        <td id="asdf" class='xxx'><%= album.user.full_name %></td>
        <td id="yyy" class='xxx'><%= link_to 'Show', album %></td>
        <td id="yyy" class='xxx'><%= link_to 'Edit', edit_album_path(album) %></td>
        <td id="yyy" class='xxx'><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

project/ImageHub/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/ImageHub/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

project/ImageHub/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="heading">Listing Albums</h1>

<%= render 'albums/albums', albums: @albums %>

<br>

<%= link_to 'New Album', new_album_path %>

<% content_for :js do %>
<script>
  $('#heading').click(function(){
    console.log(new Date())
  })
</script>
<% end %>

project/ImageHub/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

project/ImageHub/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @album.user %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>